/*
 * botapi
 *
 * Easily and directly detect and block bot activity.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Cloudmersive.APIClient.NET.BotDetection.Client;
using Cloudmersive.APIClient.NET.BotDetection.Model;

namespace Cloudmersive.APIClient.NET.BotDetection.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptchaApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create an image CAPTCHA
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <returns>ImageCaptchaGenerateResult</returns>
        ImageCaptchaGenerateResult BotCaptchaImageGeneratePost(int? characters = default(int?));

        /// <summary>
        /// Create an image CAPTCHA
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <returns>ApiResponse of ImageCaptchaGenerateResult</returns>
        ApiResponse<ImageCaptchaGenerateResult> BotCaptchaImageGeneratePostWithHttpInfo(int? characters = default(int?));
        /// <summary>
        /// Validate a CAPTCHA response from the user
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <returns>ImageCaptchaValidateResult</returns>
        ImageCaptchaValidateResult BotCaptchaImageValidatePost(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?));

        /// <summary>
        /// Validate a CAPTCHA response from the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <returns>ApiResponse of ImageCaptchaValidateResult</returns>
        ApiResponse<ImageCaptchaValidateResult> BotCaptchaImageValidatePostWithHttpInfo(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptchaApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create an image CAPTCHA
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ImageCaptchaGenerateResult</returns>
        System.Threading.Tasks.Task<ImageCaptchaGenerateResult> BotCaptchaImageGeneratePostAsync(int? characters = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create an image CAPTCHA
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ImageCaptchaGenerateResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ImageCaptchaGenerateResult>> BotCaptchaImageGeneratePostWithHttpInfoAsync(int? characters = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Validate a CAPTCHA response from the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ImageCaptchaValidateResult</returns>
        System.Threading.Tasks.Task<ImageCaptchaValidateResult> BotCaptchaImageValidatePostAsync(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Validate a CAPTCHA response from the user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ImageCaptchaValidateResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ImageCaptchaValidateResult>> BotCaptchaImageValidatePostWithHttpInfoAsync(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICaptchaApi : ICaptchaApiSync, ICaptchaApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CaptchaApi : IDisposable, ICaptchaApi
    {
        private Cloudmersive.APIClient.NET.BotDetection.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public CaptchaApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public CaptchaApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.BotDetection.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.BotDetection.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.BotDetection.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public CaptchaApi(Cloudmersive.APIClient.NET.BotDetection.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.BotDetection.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.BotDetection.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CaptchaApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CaptchaApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.BotDetection.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.BotDetection.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.BotDetection.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CaptchaApi(HttpClient client, Cloudmersive.APIClient.NET.BotDetection.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.BotDetection.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.BotDetection.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CaptchaApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CaptchaApi(Cloudmersive.APIClient.NET.BotDetection.Client.ISynchronousClient client, Cloudmersive.APIClient.NET.BotDetection.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NET.BotDetection.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.BotDetection.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Cloudmersive.APIClient.NET.BotDetection.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.BotDetection.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.BotDetection.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.BotDetection.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.BotDetection.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create an image CAPTCHA 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <returns>ImageCaptchaGenerateResult</returns>
        public ImageCaptchaGenerateResult BotCaptchaImageGeneratePost(int? characters = default(int?))
        {
            Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaGenerateResult> localVarResponse = BotCaptchaImageGeneratePostWithHttpInfo(characters);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an image CAPTCHA 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <returns>ApiResponse of ImageCaptchaGenerateResult</returns>
        public Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaGenerateResult> BotCaptchaImageGeneratePostWithHttpInfo(int? characters = default(int?))
        {
            Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (characters != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Characters", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(characters)); // header parameter
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ImageCaptchaGenerateResult>("/bot/captcha/image/generate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BotCaptchaImageGeneratePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create an image CAPTCHA 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ImageCaptchaGenerateResult</returns>
        public async System.Threading.Tasks.Task<ImageCaptchaGenerateResult> BotCaptchaImageGeneratePostAsync(int? characters = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaGenerateResult> localVarResponse = await BotCaptchaImageGeneratePostWithHttpInfoAsync(characters, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create an image CAPTCHA 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="characters">Number of characters to request that the user enter; must be 2 or more (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ImageCaptchaGenerateResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaGenerateResult>> BotCaptchaImageGeneratePostWithHttpInfoAsync(int? characters = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (characters != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Characters", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(characters)); // header parameter
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ImageCaptchaGenerateResult>("/bot/captcha/image/generate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BotCaptchaImageGeneratePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Validate a CAPTCHA response from the user 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <returns>ImageCaptchaValidateResult</returns>
        public ImageCaptchaValidateResult BotCaptchaImageValidatePost(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?))
        {
            Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaValidateResult> localVarResponse = BotCaptchaImageValidatePostWithHttpInfo(captchaID, challengeResponse, userTimeoutMilliseconds);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Validate a CAPTCHA response from the user 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <returns>ApiResponse of ImageCaptchaValidateResult</returns>
        public Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaValidateResult> BotCaptchaImageValidatePostWithHttpInfo(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?))
        {
            Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (captchaID != null)
            {
                localVarRequestOptions.HeaderParameters.Add("CaptchaID", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(captchaID)); // header parameter
            }
            if (challengeResponse != null)
            {
                localVarRequestOptions.HeaderParameters.Add("ChallengeResponse", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(challengeResponse)); // header parameter
            }
            if (userTimeoutMilliseconds != null)
            {
                localVarRequestOptions.HeaderParameters.Add("UserTimeoutMilliseconds", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(userTimeoutMilliseconds)); // header parameter
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ImageCaptchaValidateResult>("/bot/captcha/image/validate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BotCaptchaImageValidatePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Validate a CAPTCHA response from the user 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ImageCaptchaValidateResult</returns>
        public async System.Threading.Tasks.Task<ImageCaptchaValidateResult> BotCaptchaImageValidatePostAsync(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaValidateResult> localVarResponse = await BotCaptchaImageValidatePostWithHttpInfoAsync(captchaID, challengeResponse, userTimeoutMilliseconds, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Validate a CAPTCHA response from the user 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.BotDetection.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captchaID">The ID of the CAPTCHA (this is returned from the CAPTCHA generate API) (optional)</param>
        /// <param name="challengeResponse">The challenge response input text received from the user to validate if they are a person or bot (optional)</param>
        /// <param name="userTimeoutMilliseconds">The amount of time in milliseconds to allow the user to respond; if the response occurs more than this amount of time, in milliseconds, after the CAPTCHA was created, the answer will be considered invalid even if it is correct (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ImageCaptchaValidateResult)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.BotDetection.Client.ApiResponse<ImageCaptchaValidateResult>> BotCaptchaImageValidatePostWithHttpInfoAsync(string captchaID = default(string), string challengeResponse = default(string), int? userTimeoutMilliseconds = default(int?), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.BotDetection.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (captchaID != null)
            {
                localVarRequestOptions.HeaderParameters.Add("CaptchaID", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(captchaID)); // header parameter
            }
            if (challengeResponse != null)
            {
                localVarRequestOptions.HeaderParameters.Add("ChallengeResponse", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(challengeResponse)); // header parameter
            }
            if (userTimeoutMilliseconds != null)
            {
                localVarRequestOptions.HeaderParameters.Add("UserTimeoutMilliseconds", Cloudmersive.APIClient.NET.BotDetection.Client.ClientUtils.ParameterToString(userTimeoutMilliseconds)); // header parameter
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ImageCaptchaValidateResult>("/bot/captcha/image/validate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BotCaptchaImageValidatePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
