/*
 * botapi
 *
 * Easily and directly detect and block bot activity.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cloudmersive.APIClient.NET.BotDetection.Client;
using Cloudmersive.APIClient.NET.BotDetection.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.BotDetection.Model;

namespace Cloudmersive.APIClient.NET.BotDetection.Test.Api
{
    /// <summary>
    ///  Class for testing CaptchaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CaptchaApiTests : IDisposable
    {
        private CaptchaApi instance;

        public CaptchaApiTests()
        {
            instance = new CaptchaApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CaptchaApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CaptchaApi
            //Assert.IsType<CaptchaApi>(instance);
        }

        /// <summary>
        /// Test BotCaptchaImageGeneratePost
        /// </summary>
        [Fact]
        public void BotCaptchaImageGeneratePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? characters = null;
            //var response = instance.BotCaptchaImageGeneratePost(characters);
            //Assert.IsType<ImageCaptchaGenerateResult>(response);
        }

        /// <summary>
        /// Test BotCaptchaImageValidatePost
        /// </summary>
        [Fact]
        public void BotCaptchaImageValidatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string captchaID = null;
            //string challengeResponse = null;
            //int? userTimeoutMilliseconds = null;
            //var response = instance.BotCaptchaImageValidatePost(captchaID, challengeResponse, userTimeoutMilliseconds);
            //Assert.IsType<ImageCaptchaValidateResult>(response);
        }
    }
}
