/*
 * botapi
 *
 * Easily and directly detect and block bot activity.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NET.BotDetection.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.BotDetection.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.BotDetection.Model
{
    /// <summary>
    /// ImageCaptchaGenerateResult
    /// </summary>
    [DataContract(Name = "ImageCaptchaGenerateResult")]
    public partial class ImageCaptchaGenerateResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImageCaptchaGenerateResult" /> class.
        /// </summary>
        /// <param name="successful">successful.</param>
        /// <param name="captchaID">captchaID.</param>
        /// <param name="imageCaptchaPng">imageCaptchaPng.</param>
        public ImageCaptchaGenerateResult(bool successful = default(bool), string captchaID = default(string), byte[] imageCaptchaPng = default(byte[]))
        {
            this.Successful = successful;
            this.CaptchaID = captchaID;
            this.ImageCaptchaPng = imageCaptchaPng;
        }

        /// <summary>
        /// Gets or Sets Successful
        /// </summary>
        [DataMember(Name = "successful", EmitDefaultValue = true)]
        public bool Successful { get; set; }

        /// <summary>
        /// Gets or Sets CaptchaID
        /// </summary>
        [DataMember(Name = "captchaID", EmitDefaultValue = false)]
        public string CaptchaID { get; set; }

        /// <summary>
        /// Gets or Sets ImageCaptchaPng
        /// </summary>
        [DataMember(Name = "imageCaptchaPng", EmitDefaultValue = false)]
        public byte[] ImageCaptchaPng { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImageCaptchaGenerateResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CaptchaID: ").Append(CaptchaID).Append("\n");
            sb.Append("  ImageCaptchaPng: ").Append(ImageCaptchaPng).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
