/*
 * botapi
 *
 * Easily and directly detect and block bot activity.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.BotDetection.Model;
using Cloudmersive.APIClient.NET.BotDetection.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.BotDetection.Test.Model
{
    /// <summary>
    ///  Class for testing ImageCaptchaGenerateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageCaptchaGenerateResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageCaptchaGenerateResult
        //private ImageCaptchaGenerateResult instance;

        public ImageCaptchaGenerateResultTests()
        {
            // TODO uncomment below to create an instance of ImageCaptchaGenerateResult
            //instance = new ImageCaptchaGenerateResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageCaptchaGenerateResult
        /// </summary>
        [Fact]
        public void ImageCaptchaGenerateResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageCaptchaGenerateResult
            //Assert.IsType<ImageCaptchaGenerateResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'CaptchaID'
        /// </summary>
        [Fact]
        public void CaptchaIDTest()
        {
            // TODO unit test for the property 'CaptchaID'
        }

        /// <summary>
        /// Test the property 'ImageCaptchaPng'
        /// </summary>
        [Fact]
        public void ImageCaptchaPngTest()
        {
            // TODO unit test for the property 'ImageCaptchaPng'
        }
    }
}
