/*
 * botapi
 *
 * Easily and directly detect and block bot activity.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.BotDetection.Model;
using Cloudmersive.APIClient.NET.BotDetection.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.BotDetection.Test.Model
{
    /// <summary>
    ///  Class for testing ImageCaptchaValidateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageCaptchaValidateResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageCaptchaValidateResult
        //private ImageCaptchaValidateResult instance;

        public ImageCaptchaValidateResultTests()
        {
            // TODO uncomment below to create an instance of ImageCaptchaValidateResult
            //instance = new ImageCaptchaValidateResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageCaptchaValidateResult
        /// </summary>
        [Fact]
        public void ImageCaptchaValidateResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageCaptchaValidateResult
            //Assert.IsType<ImageCaptchaValidateResult>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
    }
}
